services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    restart: always
    environment:
      - COLLECTIONS=${COLLECTIONS}
      - EVIL_BIT_BUCKET=true
      - TZ=${TIMEZONE:-UTC}
    volumes:
      - ./config:/etc/crowdsec
      - data:/var/lib/crowdsec/data
      - /logs/npm:/var/log/npm:ro
      - ./acquis.d:/etc/crowdsec/acquis.d:ro
    network_mode: host

volumes:
  data:
    name: crowdsec-data